server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-signup
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/member/signup
        - id: auth-service-login
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/member/login
        - id: auth-service-protected
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/member/**
          filters:
            - AuthorizationHeaderFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

# jwt setting
jwt:
  accessKey: TestAccessKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio