server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service  # ???? ???? ?? ???? ??
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/member/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

# jwt setting
jwt:
  accessKey: TestAccessKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
  refreshKey: TestRefreshKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
  accessExpiration: PT60M  # 60? (PT60M)
  refreshExpiration: PT1080M  # 10080? (7?) (PT10080M)