server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service  # ???? ???? ?? ???? ??
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/member/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG